### ISSUE TITLE
Route not working

### ISSUE THREAD

**Issue by keyoti** [ethanent/coroute#1]
Here's my config

```
{
	"listen": {
		
		"my_http": {
			"host": "localhost",
			"port": 8001
		}
	},
	"route": [
		{
			"from": {
				"server": "my_http",
				"host": "localhost"
			},
			"to": "http://localhost:80"
		}
	]
}
```

I'm hitting http://localhost:8001/ in my browser, expecting it to redirect to my IIS on port 80.

However I'm getting

> Coroute 404: No route found

Did I go wrong with the config?  I tried debugging your code, put a breakpoint inside the `find`

```
module.exports = class CorouteInternalServer {
	constructor (name, options, routes) {
		this.name = name
		this.options = options
		this.routes = routes.filter((route) => !(route.from.hasOwnProperty('server') && route.from.server !== name)) // Filter out routes not delegated to this server.

		this.app = new V()

		this.app.use(V.route)

		this.app.add(async (req, res) => {
			const useRoute = this.routes.find((route) => {
				if (route.from.hasOwnProperty('server') && route.from.server !== this.name) {
					return false
				}
```

What I found though is that `this` is undefined.  I'm a NodeJS beginner, but does this work in your Node version?  I'm running v8.9.3 (I have to run that v)

This https://stackoverflow.com/questions/7874723/maintaining-the-reference-to-this-in-javascript-when-using-callbacks-and-closu is saying that you can't access `this` inside a closure - so I don't know what's going on here.

Thank you!

**Comment by keyoti** [comment]
FYI the real problem I was having was not realising that the `host` in the `route` configuration should have the port number included. I missed that because your example uses port 80 and so you wouldn't use `:80` there.

**Comment by ethanent** [comment]
Ah, ok, got it! Glad you figured it out! I'll review the docs to see if the explanation for the host specifier needs more emphasis on the use of the [HTTP Host](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) header.

**Comment by keyoti** [comment]
You should probably also say that the `host` property in the route is optional, that isn't clear in the docs.  Let me know what you think about iss #2 and if you like I will submit a PR with these changes.
