### ISSUE TITLE
Debugging why my HTTPS server isn't working.

### ISSUE THREAD

**Issue by keyoti** [ethanent/coroute#2]
Hi, my HTTPS server just isn't doing anything.  Here's my config
```

{
	"listen": {
		"my_https": {
			"https": {
				"key": "C:\\path\\localhost.key",
				"cert": "C:\\path\\localhost.crt"
			},
			"port": 4443,
			"host": "localhost"
		}
	},
	"route": [
		{
			"from": {
				"server": "my_https",
				"host":"localhost:4443"
				
			},
			"to": "http://localhost:80"
		}
	]
}
```

I hit https://localhost:4443/ and get ERR_CONNECTION_CLOSED in chrome (which I presume means coroute accepted the request but didn't know what to do with it).

Is there something obviously wrong with my config?

If not, I'm trying to debug it, but I appear to be hopeless at Node :) because I can't get past this, maybe you can help:

CorouteInternalServer has this function

```
async startServer () {
		if (this.options.hasOwnProperty('https')) {
			this.internalServer = https.createServer({
				'key': (await pfs.readFile(path.resolve(process.cwd(), this.options.https.key))).toString(),
				'cert': (await pfs.readFile(path.resolve(process.cwd(), this.options.https.cert))).toString()
			}, this.app.serverHandler)
		}
		else {
			this.internalServer = http.createServer(this.app.serverHandler)
		}

		this.app.internalServer.listen(this.options.port, this.options.host, () => {
			return
		})
	}
```

I'm guessing that `this.app.serverHandler` handles the requests coming in, and that is where you make a new request to the target server(?).  However I cannot find where `this.app.serverHandler` is assigned, so I can't take a look at it's function to watch requests coming in.

How should I proceed?  Thanks.

**Comment by keyoti** [comment]
In CorouteInternalServer I put a breakpoint inside the function being passed to add

	```
	this.app.add(async (req, res) => {
			console.log(req.body)
			const useRoute = this.routes.find((route) => {
```

but it's not called, how can I figure out why, where should I look?

**Comment by keyoti** [comment]
Ok, I believe I have it working, but I had to change your source code, which I don't understand - could you please comment on what I've done?

In CorouteInternalServer.

      async startServer () {
		if (this.options.hasOwnProperty('https')) {
			this.internalServer = https.createServer({
				'key': (await pfs.readFile(path.resolve(process.cwd(), this.options.https.key))).toString(),
				'cert': (await pfs.readFile(path.resolve(process.cwd(), this.options.https.cert))).toString()
			}, this.app.serverHandler).listen(this.options.port)
			
		}
		else {
			this.internalServer = http.createServer(this.app.serverHandler)
		}

		this.app.internalServer.listen(this.options.port, this.options.host, () => {
			return
		})
	}

I added `.listen(this.options.port)` at the end of the createServer call.  This is the documented use of the `https` server, so I don't understand how it was working for you before that change?

I see the call to `this.app.internalServer.listen` but that seems to be a different object, what is the relationship of `this.app.internalServer` to `this.internalServer.listen`?

Really I need to know if my change is suitable?  Is it some deficiency in my config that caused it to be required?

Thanks

**Comment by ethanent** [comment]
Hmm. I will be looking at this soon. There clearly may be internal issues with the handling of HTTPS certificates / servers.
